### ISSUE TITLE
Benefit over existing code outline extensions?

### ISSUE THREAD

**Issue by bm-stschneider** [oleg-shilo/codemap.vscode#1]
I was just asking myself, what benefits have your implementation over the already existing ones like?

https://github.com/patrys/vscode-code-outline

**Comment by oleg-shilo** [comment]
I haven't tested that extension. The extension home page does not contain any screenshot so I didn't identify it as belonging to the same category. 

Anyway I just tested it now and indeed it is a good extension that brings very similar functionality as _Code Map_. Right now I can pick only a two differences:
* _vscode-code-outline_ uses nested tree view for presentation and _CodeMap_ a flat tree view with indentation to indicate the nesting level. I have implemented both _flat_ and _nested_ approach but since VSCode still has the problem with uncontrollable TreeViewNode state change on clicking I opted to the more predictable flat tree view. But when VSCode team addresses the problem (https://github.com/Microsoft/vscode/issues/34130) I will enable the true nesting and add node icons. 

* _vscode-code-outline_ has  a more comprehensive parsing algorithm. _CodeMap_ has adequate but very simplistic TS parsing algorithm implemented at this stage. 

However the major distinction point is that CodeMap is a port of the [Sublime CodeMap plugin](https://github.com/oleg-shilo/sublime-codemap/blob/master/README.md)  plugin, which is rather a code mapping infrastructure then a one off specific syntax product. 

Thus CodeMap comes with:
* A few built-in dedicated mappers (syntax specific algorithms): TS, Python, C#.  
* An universal RegEx-based mapper that can be configured (settings file) to handle new languages
* Users can implement (with TS) their own dedicated mappers (e.g. for ini file syntax) and extend CodeMap with new syntax support. 

In a few days I will be releasing Python mapper. Then it will be turn for Roslyn-based C# mapper, and after that custom mappers and eventually the _universal mapper_ support.  

Thus if you are only only interested in TypeScript the probably you can stick with  _vscode-code-outline_. Otherwise, keep an eye on _CodeMap_.

**Comment by bm-stschneider** [comment]
Thanks for the elaborate answer. This was very informative.
