### ISSUE TITLE
Custom mapper doesn´t work

### ISSUE THREAD

**Issue by Kampi** [oleg-shilo/codemap.vscode#10]
I want to create a custom mapper for assembly language (primary goal) so I follow your example in the wiki to create a generic wrapper for a file extension (I try it with your markdown example first).
My file `main.x` looks like this

<div>
# Test <br>
### Test3 <br>
<br>
</div>   

I have a `mapper_X.js` on my desktop (complete path C:\Users\Daniel\Desktop\mapper_X.js)
` 
"codemap.md": [
    {
      "pattern": "^(\\s*)### (.*)",
      "clear": "##",
      "prefix": " -",
      "icon": "level3"
    },
    {
      "pattern": "^(\\s*)## (.*)",
      "clear": "##",
      "prefix": " ",
      "icon": "level2"
    },
    {
      "pattern": "^(\\s*)# (.*)",
      "clear": "#",
      "prefix": "",
      "icon": "level1"
    },
    {
      "pattern": "!\\[image\\]",
      "clear": "![image]",
      "prefix": "<image>",
      "icon": "none"
    }
  ]
`
VS code marks the ":" in '"codemap.md": [' red and say ";" expected. Why?

I also add `"codemap.X": "C:\\Users\\Daniel\\Desktop\\mapper_X.js",` to my `settings.json`. VS code marks `codemap.X` green and say `Unknown configuration setting`.

And I don´t get any result in my `Code Map` window with the above example.

What goes wrong here?

Thank you!

**Comment by oleg-shilo** [comment]
The idea of any extension configuration is that it is defined in the JSON not JS file. That's why you have a syntax error.

The config file is also must be present in the special location. Not in the desktop folder.

What you need to do is to use VSCode to start editing user settings. This will create the json file where you will need to paste your settings content.

**Comment by swlsong** [comment]
Could you please tell me what I am doing wrong. I first copied the definition of codemap.md to user settings, renamed it to codemap.X, and then created a test.X file where I input some markdown headlines, but they don't appear in the left pane. I make this trail to make the step as small as possible.

"codemap.X": [
    {
      "pattern": "^(\\s*)### (.*)",
      "clear": "###",
      "prefix": " -",
      "icon": "level3"
    },
    {
      "pattern": "^(\\s*)## (.*)",
      "clear": "##",
      "prefix": " ",
      "icon": "level2"
    },
    {
      "pattern": "^(\\s*)# (.*)",
      "clear": "#",
      "prefix": "",
      "icon": "level1"
    },
    {
      "pattern": "!\\[image\\]",
      "clear": "![image]",
      "prefix": "<image>",
      "icon": "none"
    },
    {
      "pattern": "!\\[\\]",
      "clear": "![]",
      "prefix": "<image>",
      "icon": "none"
    }
  ],

**Comment by oleg-shilo** [comment]
The following is an extract from [Wiki](https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers/_edit) that I have created to assist you and others in the situatuion like yours:

----

### How To 

_Hint_<br>
When creating a custom generic mapper it is difficult to get it right from the first hit because your mapper will depend on the correctness of your regular expressions. Which in turn usually start working only after a few attempts. Thus it will be much easier if you implement a very generic mapper first and only then then start refining your regex patterns.

#### Creating simple generic mapper
Assume we need to create a mapper for the files with the extension '.x'. 
Follow these very simple steps.

- Open settings page<br>
  ![](https://user-images.githubusercontent.com/16729806/53282653-d5997b00-378e-11e9-9f2a-d03a1dbc64fd.png)
- Open _settings.json_ file<br>
  ![](https://user-images.githubusercontent.com/16729806/53282666-ffeb3880-378e-11e9-8cc3-96467b357bc8.png)
- Insert generic pattern
  ```json
    . . .
    "codemap.x": [
      {
        "pattern": "function \\w*",
        "icon": "function"
      }
    ],
    . . .
  ```
  The configuration above will trigger building the code tree with nodes corresponding every line that starts from "function " word.
- Trigger code map generation by pressing the refresh button:<br>
  ![image](https://user-images.githubusercontent.com/16729806/53282866-121aa600-3792-11e9-9573-19aac9df6645.png)

- Use one of the [online regex testing tools](https://www.regexpal.com/)  to refine your regex expression to serve your specific syntax.

The regex from the sample above was taken from the PowerShell syntax mapper:
```json
"codemap.ps1": [
  {
    "pattern": "function \\w*",
    "clear": "function ",
    "suffix": "(...)",
    "icon": "function"
  }
],
```

**Comment by swlsong** [comment]
I accidentally found the solution. The pattern suffix doesn't need to be in the same case as the file extension. If I name the pattern as "codemap.x", and the file as "test.X", it works. If I name the pattern as "codemap.X", it doesn't. So, I can use your extension now. Thank you!

**Comment by oleg-shilo** [comment]
Great.

If you are happy with your R mapper, you can share it and I will include it into the default distro.

**Comment by swlsong** [comment]
Thank you for the encouragement. I won't dare to call my effort a R mapper, though. As an appreciation of your valuable extension, I want to show that even some most rudimentary pattern for the generic mapper can help a lot. With the following example, I get a wonderful list of functions or unit tests. 

Could you please tells me the possible values for the key "icon"? It would help if I or others go on refining the patterns. Thank you!

```
  "codemap.r": [
    {
      "pattern": ".*<-.*function.*",
      "icon": "function"
    },
    {
      "pattern": ".*test_that.*",
      "icon": "function"
    }
  ],
```

**Comment by swlsong** [comment]
I found the defined values for the key "icon" in your wiki and therefore deleted my question from my last comment.

> icon - name of the predefined icon:
> 
> class
> interface
> function
> property
> document
> level1
> level2
> level3
> none

**Comment by oleg-shilo** [comment]
Excellent, can you also share any realistic/representative R source that I can take, pass through the mapper and use the screenshot for the documentation? It would save me the time for chasing it online.

**Comment by oleg-shilo** [comment]
Don't worry. I got a good code sample now.

**Comment by swlsong** [comment]
Great, it's very kind of you. I would have used some scripts from the testthat package at https://github.com/r-lib/testthat/tree/master/R.

**Comment by oleg-shilo** [comment]
done. he latest version of CopdeMap contains default support for R.

https://github.com/oleg-shilo/codemap.vscode/blob/dd1c1102e0bc6fcb305024089ed61e5f6c753f8e/package.json#L81-L97

Though if you have your mapping defined in _settings.json_ it will take the precedence over the default configuration. To check out the actual configuration you can execute the new "Show mappers" command:

![image](https://user-images.githubusercontent.com/16729806/53450375-28fe1880-3a70-11e9-8f00-29b52f672bb1.png)

**Comment by swlsong** [comment]
The new version is automatically installed. I love it and removed my pattern definition. Thank you!

**Comment by oleg-shilo** [comment]
Actually VSCode supposed not to remove custom user configuration on extension update. This si rather odd and... unfortunately outside of my control. 

Though you can always restore your custom mapper patterns by specifying them (again) in the _settings.json_ file.

**Comment by swlsong** [comment]
No, no, I myself have removed it because yours already does more than mine. 

I want to share some information which is off topic in this issue. I newly switched to the portable version of vscode to avoid profile roaming. I noticed 

> AppData\Roaming\Code\User\codemap.user\syntaxer\1.2.1.0\syntaxer.exe

 is currently the only piece that does not live in the data folder of the portable vscode.

**Comment by oleg-shilo** [comment]
> No, no, I myself have removed it ...

Cool, then it makes sense :)

> ...is currently the only piece that does not live in the data folder...

Correct. `syntaxer.exe` is a server that is running in background and it needs to be deployed outside of extension dir so it does not interfere with the upgrading steps. When thy are executed.

`CodeMap` extension deploys it to the dedicated versioned sub folder of the VSCode user folder. The very same folder where persistent user settings are stored. And according VSCode [documentation](https://vscode.readthedocs.io/en/latest/getstarted/settings/) this folder is determined as below:

![image](https://user-images.githubusercontent.com/16729806/53803033-8d9d0400-3f97-11e9-97ef-55bc4d51da43.png)

I am almost confident that even portable VSCode installation stores user data there as well.

**Comment by swlsong** [comment]
Thank you. It's very kind of you to response every time in great detail. I searched but didn't find settings.json in AppData\Roaming\Code and its subfolders. But you must know much more than me.

**Comment by oleg-shilo** [comment]
Not a problem. :)

You did not found `settings.json` probably because in case of portable install this file is stored somewhere else. I actually would appreciate if you tell me where exactly.

You can find it out by follow these very simple steps.

- Open settings page<br>
  ![](https://user-images.githubusercontent.com/16729806/53282653-d5997b00-378e-11e9-9f2a-d03a1dbc64fd.png)
- Open _settings.json_ file<br>
  ![](https://user-images.githubusercontent.com/16729806/53282666-ffeb3880-378e-11e9-8cc3-96467b357bc8.png) 

Now note the file full path VSCode active doc `settings.json`.

I am trying to get this info because `syntaxer.exe` is a user asset (similarly to `settings.json`) so it needs to be stored outside of the "extensions" folder and I simply don't know how VSCode solves the location problem for `settings.json` file.  But if I do, then it can be an opportunity to store `syntaxer.json` at the same location.

**Comment by swlsong** [comment]
It's in <vscode directory>\data\user-data\User\settings.json.

**Comment by oleg-shilo** [comment]
Thank you.

**Comment by swlsong** [comment]
You are welcome and thank you again for your extension!

**Comment by oleg-shilo** [comment]
I am closing this issue but you can reopen it if any further help is required .
