### ISSUE TITLE
Can CodeMap display in Explorer Activity

### ISSUE THREAD

**Issue by derekwallace** [oleg-shilo/codemap.vscode#23]
HI,
Can the CodeMap explorer have a setting to allow where its displayed.
Some screen shots show it in the Exporer activity.
However now its in its own activity on the activity bar.

A setting to control this would be great.

Thanks
Derek

**Comment by oleg-shilo** [comment]
Unfortunately it is not possible. 

The placement of any plugin view  is hard-codded in the plugin's `package.json`.  Thus it's either its own view or in the main explorer.

And since 
- CodeMap can be relatively packed with the content
- Main explorer is already crowded
- VSCode introduced the mechanism and started encouraging authors to move their heavy plugin panels into the dedicated views 

A few releases ago CodeMap has been moved in its own view.

Though thank you for letting me know. I have updated the readme.md to reflect the correct location of the plugin view:

![image](https://user-images.githubusercontent.com/16729806/67156959-16bf4a80-f371-11e9-841b-dee1b9ba364e.png)
