### ISSUE TITLE
Show current location of cursor in file

### ISSUE THREAD

**Issue by arnoudplantinga** [oleg-shilo/codemap.vscode#29]
Issue Type: Feature Request

It would be helpful to highlight in the codemap the current location of the cursor in the file.

**Comment by oleg-shilo** [comment]
I will check but it might be harder than it seems. 
AFAIR the intercepting the caret location change is problematic. Yes VSCode UI model is extremely limited. At least it was when CodeMap was developed. But even standard thing like a custom tooltip over a treeview item is still impossible with VSCode.

**Comment by oleg-shilo** [comment]
As I was afraid VSCode just does not have an event that can be used by the extensions to detect the caret position change: https://code.visualstudio.com/api/references/vscode-api.

I will still keep this issue _open_ so when/if VSCode gains the required event interface the requested feature will be implemented.

**Comment by MagTun** [comment]
I wanted to request the same feature, too bad it's not yet possible.

Maybe a work around could be to use markers in the scroll bar of the editor for each codemap title (like the search or the debug do), with maybe a hover popup to know which marker correspond to which title...

**Comment by oleg-shilo** [comment]
Getting the code from the caret position is not a problem. It can be done even easier than analyzing the scrollbar.

The problem is that VSCode API does not have an event for caret position change. Thus it's not possible to detect when a new treeview node needs to be selected.

But... it can be done manually. Thus I have just released the v1.13.0 that has a command for revealing the tree view node that corresponds to the code at the current caret position in the active document.

The command can be executed either via Alt+L or a button at the top of the CodeMap view:

![image](https://user-images.githubusercontent.com/16729806/83263253-a67b8000-a201-11ea-8e63-cef1087330a2.png)

**Comment by AlencarGabriel** [comment]
Hello @oleg-shilo ,

I found a solution so that I no longer need to use the button.

Just use the event `vscode.window.onDidChangeTextEditorSelection`. 

Whenever the course is moved, this event is triggered.

**Comment by MagTun** [comment]
@AlencarGabriel, how did you use this event? Which file did you edit? Thanks!

**Comment by AlencarGabriel** [comment]
I did a test using this approach:

![image](https://user-images.githubusercontent.com/10109480/86630274-fd176f00-bfa2-11ea-8908-e3b18436470e.png)

The `editor` variable contains the necessary attributes to identify the user's selection.

**Comment by oleg-shilo** [comment]
Thanks, will test it and add "auto track location" as an option.

**Comment by oleg-shilo** [comment]
Done.

Implemented in Release v1.14.0.

Thank you for your contribution.

**Comment by AlencarGabriel** [comment]
Wonder @oleg-shilo ,

worked perfectly. Glad to have helped!
