### ISSUE TITLE
Set Indentation with generic mapper

### ISSUE THREAD

**Issue by jharris1314** [oleg-shilo/codemap.vscode#32]
Can you set indentation with the generic mapper?  If so, how?

**Comment by oleg-shilo** [comment]
If you are using regular tree view rendering then you cannot really control it. TreeView does.

However if you have TextMode enabled (my preferred mode btw  😄) then you can specify the size of indent by defining it as a non-whitespace string of any size:

![image](https://user-images.githubusercontent.com/16729806/80915255-6953d780-8d94-11ea-8cff-771699dc1099.png)

And just to give you the idea about the difference between _TreeView_ and _Text_ mode:

_TreeView mode:_

![image](https://user-images.githubusercontent.com/16729806/80915293-b89a0800-8d94-11ea-9310-5c7866aeaade.png)

_Text mode:_

![image](https://user-images.githubusercontent.com/16729806/80915343-1af30880-8d95-11ea-89c9-3d5c70f13717.png)

**Comment by jharris1314** [comment]
Thank you for the quick response.  I am using Text mode.  I am adding a prefix of "   " (multiple spaces) for each item in the settings.json, but the spaces are not showing up in the Codemap Explorer.  

`{
          "pattern": "LAYER:\\w*",
          "prefix": "   ",
          "icon": "function"
  },`

**Comment by oleg-shilo** [comment]
You cannot use "multiple spaces":

> indent by defining it as a non-whitespace string of any size

TreeView always swallows spaces. You need to use any unicode character that is not a space and yet does not render anything on the screen. 
Thus the line below is a string of three characters 'U-00A0' 
`   `
You can also copy it from codemap  
![image](https://user-images.githubusercontent.com/16729806/80964584-8059fe80-8e54-11ea-8cc2-d4cd8e9bfb90.png)

**Comment by jharris1314** [comment]
Copying them from codemap worked.  Thanks for the help.  This extension is incredibly helpful for navigating gcode.  

Suggestion: It would be very useful if you could indent the icons in text mode.

**Comment by oleg-shilo** [comment]
> Suggestion: It would be very useful if you could indent the icons in text mode.

Sorry mate, not possible :)

The text mos is intended to overcome rather very limited rendering capabilities of TreeView by allowing custom indent (like you did) in the text area of the tree node. We need it because TreeView does not allow us to customize the indent any other way. So we insert the empty text to emulate indent. 

But the true indent, the one that shifts icons to the right side is just not customizable. Well at least with this state of VSCode API

**Comment by juanbretti** [comment]
> The text mos is intended to overcome rather very limited rendering capabilities of TreeView by allowing custom indent (like you did) in the text area of the tree node. We need it because TreeView does not allow us to customize the indent any other way. So we insert the empty text to emulate indent.

Sorry, but I don't find it clear. I want to use the **TreeView** and have indentation using my **custom** mapping. Is that possible?

My mapping for **Python** looks like:

        {
            "pattern": "^(\\s*)#### (.*)----",
            "clear": "#|----",
            "prefix": "  ",
            "icon": "level3"
        },
        {
            "pattern": "^(\\s*)### (.*)----",
            "clear": "#|----",
            "prefix": " ",
            "icon": "level2"
        },
        {
            "pattern": "^(\\s*)## (.*)----",
            "clear": "#|----",
            "icon": "level1"
        },

Thanks!

**Comment by oleg-shilo** [comment]
Yes it is. 
If you are using "codemap.textMode" then you can set `codemap.textModeLevelPrefixJust` to any text you want and it will become your indent text multiplied by the indent level value. 

If you are not using "codemap.textMode" then nothing you can do as VSCode does not allow that

**Comment by juanbretti** [comment]
@oleg-shilo , thank you for your reply and your time. I really appreciate it.
To be honest, I don't know where should I add that `codemap.textModeLevelPrefixJust`. Can you give me some advice?
I tried to check if that line was in another example inside the repo, but I wasn't able to find it.
Thanks!

**Comment by oleg-shilo** [comment]
It's OK. You are welcome :o)

These are the extension setting. You can edit them by accessing through the extensions panel: 
![image](https://user-images.githubusercontent.com/16729806/93476371-12166400-f93d-11ea-8598-6003f78aeca7.png)

Or directly in the settings file:
![image](https://user-images.githubusercontent.com/16729806/93476470-2eb29c00-f93d-11ea-9c9a-bc02eee02f32.png)

The setting that you are looking for is `codemap.textModeLevelPrefix`.
![image](https://user-images.githubusercontent.com/16729806/93476873-a1237c00-f93d-11ea-8540-26b65f8fc93b.png)

if you put lat's say `www` there then it will become your single level indent:

```
www<level1 tree view item>
wwwwww<level3 tree view item>
wwwwwwwww<level3 tree view item>
```

But of course you want to put invisible white space characters (e.g. spaces). But VSCode trims them so you need to put something else that is invisible but not a trim-able white space. I took a character 3 characters `U+00A0` that I copied from CrahacterMap app of Windows. Thus if you want to double the indent then you simply convert the config value (by using clipboard) into 6 characters `U+00A0`. 

Change the setting and see how it affects the appearance.  This way you can find the solution you want.

**Comment by juanbretti** [comment]
@oleg-shilo , thank you very much for your response.
But what I want is to be able to have this triangle:

<img width="281" alt="what i want" src="https://user-images.githubusercontent.com/10165911/93662761-c5c54400-fa62-11ea-8773-033dc44be4aa.png">

I have this on `settings.json`:

```
"codemap.py": [
    
    {
        "pattern": "^(\\s*)#### (.*)----",
        "clear": "#|----",
        "prefix": "  ",
        "icon": "level3"
    },
    {
        "pattern": "^(\\s*)### (.*)----",
        "clear": "#|----",
        "prefix": " ",
        "icon": "level2"
    },
    {
        "pattern": "^(\\s*)## (.*)----",
        "clear": "#|----",
        "icon": "level1"
    },
    {
        "pattern": "(?<![^\\r\\n\\t\\f\\v .])class (.*?)[(|:]",
        "clear": "class|:|\\)|\\(",
        "role": "class",
        "icon": "class"
    },
    {
        "pattern": "def (.*?)[(|:]",
        "clear": "def|:|\\(|\\)",
        "role": "function",
        "icon": "function"
    },
    {
        "pattern": "^(\\s*)# TODO: (.*)",
        "clear": "# TODO: ",
        "icon": "document"
    }
],
"codemap.location": "explorer",
"codemap.textMode": false,
```

And as example, I have this **Python** code:

```
## hola ----
### h2ola ----
def h2ola()
    pass
    def test():
        pass
```

But the result I have is:

<img width="195" alt="no triangle" src="https://user-images.githubusercontent.com/10165911/93662821-41bf8c00-fa63-11ea-9f39-bf5af23ed49d.png">

As you can see, I don't have the triangle at "h2ola".
Is it possible to have it? As the same I have for `def ():`

Thanks!

**Comment by oleg-shilo** [comment]
The triangle symbol is an indicator of the node having children nodes. BTW you have no control over the appearance of parent node. TreeView does it for you.
   
So the appearance of the first **h2ola** node (without the triangle) is correct as it does not have children.
The appearance of the second **h2ola** node (with the triangle) is also correct as it does have children.

**Comment by juanbretti** [comment]
What I would like to do, is these where father and child:
```
## hola ----
### h2ola ----
```
Is that possible?
Or at least, the _orange square_ to be indented to the right.

**Comment by oleg-shilo** [comment]
> As you can see, I don't have the triangle at "h2ola".

So what you actually wanted to say is "As you can see, I don't have the triangle at **"hola".** Is it right?

**Comment by juanbretti** [comment]
@oleg-shilo , you are right... My example was confusing.
Let's start again.

<img width="570" alt="Screenshot 2020-09-19 143742" src="https://user-images.githubusercontent.com/10165911/93667397-d0dd9b80-fa85-11ea-9f24-74188f461fd2.png">

I have this **Python** code:

```
## Comment_level_1 ----
### Comment_level_2 ----
def function_1()
    pass
    def function_2():
        pass
```

I want to have a triangle (to expand and contract) the comment called "**Comment_level_1**".
And want to have Comment_level_2 with an indentation.
Something like this:

<img width="570" alt="end" src="https://user-images.githubusercontent.com/10165911/93667744-709c2900-fa88-11ea-9503-b36e8dfb6774.png">

Do you think is possible?

**Comment by oleg-shilo** [comment]
:) The yes. The right description of your expectations is "As you can see, I don't have the triangle at "hola"."

All good then we are on the same page. I think it is what VS code supposed to do already as it is expected to nest level2 in the Level1 node.

I will revisit the nesting algorithm. May be there is a defect. Will let you know.

**Comment by oleg-shilo** [comment]
OK, there is a logical problem with your scenario. 

You are trying to build a mapper for the syntax that does not have nesting level defined with the indent. Python code does it - every nested item is indented with an extra white spaces (e.g. 4 spaces) comparing to the parent position in the line. But your code comments do not.

Indent is how regex based generic mapper (one that you are using) knows which regex matching line is a parent and which one is a child.

Thus if you change your code as below, you will see that it produces the desired treeView output:
```py
## Comment_level_1 ----
    ### Comment_level_2 ----
def function_1()
    pass
    def function_2():
        pass
```  

Of course placing such an artificial indent on the Python comment line may not make sense in some cases. 

Anyway a dedicated TS/JS mapper is a much better choice when your syntax is unable to encode the nesting via indent (Markdown). And this is exactly what [Markdown mapper](https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers#mapping-with-a-dedicated-mapper) uses.

So normally I would advice you to go with a dedicated mapper but...

I see that the ability to deal with non-indented content from a generic mapper may be beneficial in some cases. Thus I have extended the generic mapper definition with an extra value `levelIndent`. This value defines not physical but logical indent that is assigned to the matching item that is non-indented at otherwise at runtime. For the cases of mixed indented/non-indented syntax like yours, this value needs to match the indent of the main (indented) syntax. Thus if your Python used 4 spaces to define first level nesting should be `4`. And the second level - `8`.

When applied to your sample it produces the desired outcome:

![image](https://user-images.githubusercontent.com/16729806/93708093-d9fa6580-fb76-11ea-939a-f99324e52c95.png)

The enhancement will be available in the very next release.

**Comment by juanbretti** [comment]
@oleg-shilo , I will be waiting for the next release! Thank you!

**Comment by juanbretti** [comment]
Works very good! Thanks!
