### ISSUE TITLE
C# isn't Working

### ISSUE THREAD

**Issue by Edemilorhea** [oleg-shilo/codemap.vscode#69]
I want to ask why my c# file can't get any method in Explorer of CodeMAP

I'm use ASP.Net 4.5 fraemwork.

I don't know which part is wrong.

![螢幕擷取畫面 2022-06-15 012543](https://user-images.githubusercontent.com/92776711/173639371-d57eca14-47d0-433e-a329-d26927bce497.png)

Thank you!!

**Comment by Edemilorhea** [comment]
> 

sorry I'm reply late.

I didn't see any console log and error messages.

But it is working on Json syntax

And This problem just on my home PC, it is perfact on my company PC.

But the setting is smae casue I had use account sync setting.

I am try out to check what is it happend

**Comment by oleg-shilo** [comment]
you will need to have .NET5 (or higher) installed.
Do you have it on that PC?

**Comment by Edemilorhea** [comment]
Yes I already installed .NET6 on my Pc by Visual Studio.

**Comment by oleg-shilo** [comment]
The extension uses Roslyn to do the C# code parsing (mapping). And since this functionality is implemented outside of the extension codebase, you can test it even without VSCode.
And as a simple experiment, you can do this:

1. Start Roslyn server:
`dotnet .\syntaxer.core.dll -port:18004 -listen -timeout:60000`
![image](https://user-images.githubusercontent.com/16729806/177137300-0506ac35-ef6c-4224-8f09-a0007615a227.png)

2. Start the Roslyn client (this is what the extension does under the hood):
`dotnet .\syntaxer.core.cli.dll 18004 -op:codemap_vscode -script:<your_script_full_path>`
![image](https://user-images.githubusercontent.com/16729806/177137534-a8513547-31ce-4768-a457-2b9c044b1131.png)

If everything works then your client app will send the mapping request. Receives and prints the response. 
The image above shows the mapping response for the following script code:
```C#
using System;

namespace A
{
    class Test
    {
        void Foo()
        {
            Console.WriteLine("Hello ...");
        }
    }
}
```
Otherwise, you will see the error why it does not work.

**Comment by Edemilorhea** [comment]
> The extension uses Roslyn to do the C# code parsing (mapping). And since this functionality is implemented outside of the extension codebase, you can test it even without VSCode. And as a simple experiment, you can do this:
> 
> 1. Start Roslyn server:
>    `dotnet .\syntaxer.core.dll -port:18004 -listen -timeout:60000`
>    ![image](https://user-images.githubusercontent.com/16729806/177137300-0506ac35-ef6c-4224-8f09-a0007615a227.png)
> 2. Start the Roslyn client (this is what the extension does under the hood):
>    `dotnet .\syntaxer.core.cli.dll 18004 -op:codemap_vscode -script:<your_script_full_path>`
>    ![image](https://user-images.githubusercontent.com/16729806/177137534-a8513547-31ce-4768-a457-2b9c044b1131.png)
> 
> If everything works then your client app will send the mapping request. Receives and prints the response. The image above shows the mapping response for the following script code:
> 
> ```cs
> using System;
> 
> namespace A
> {
>     [Authorize]
>     class Test
>     {
>         void Foo()
>         {
>             Console.WriteLine("Hello ...");
>         }
>     }
> }
> ```
> 
> Otherwise, you will see the error why it does not work.

hello oleg-shilo I'm success to activated extention.

I found my coumputer dosen't Start Rosyln script, seems like the Script path have problem, it dosen't mapped to right path.

however it is working now.

thanks your helpful.
