### ISSUE TITLE
[help]how to use match group from "pattern" key in other key?

### ISSUE THREAD

**Issue by iamqiz** [oleg-shilo/codemap.vscode#73]
for example:
want to match line : aaa/bbb/ccc
use pattern: bbb/(.\*)
here group (.*) will match "ccc"
how can I use the group in other key, for example  , "clear" "prefix" ?

**Comment by iamqiz** [comment]
i think this feature is very important ,if not support, please support ,thanks!😘

**Comment by oleg-shilo** [comment]
Regex-based mappers (generic mappers) are a very convenient way of creating custom mappers without writing the code but defining the mapping rules via configuration. Though they are limited because of their declarative nature and cannot be used for advanced mapping scenarios. 

In such cases, you should dedicate mappers (see [here](https://github.com/oleg-shilo/codemap.vscode/wiki/Adding-custom-mappers#mapping-with-a-dedicated-mapper)) where you can rely on the full power of the programming language.

**Comment by iamqiz** [comment]
Oh nice! thanks for your help !!!!!
