### ISSUE TITLE
Minimize Code Map - Keyboard Shortcut?

### ISSUE THREAD

**Issue by KyleKing** [oleg-shilo/codemap.vscode#8]
Thanks for bringing this functionality to VS Code! I came from Sublime and loved sublime-codemap

Would it be possible to have a shortcut or option to collapse or minimize the code map view?

I mapped <kbd>ctrl</kbd> <kbd>shift</kbd> <kbd>e</kbd> chord <kbd>f</kbd> to Focus File View and <kbd>ctrl</kbd> <kbd>shift</kbd> <kbd>e</kbd> chord <kbd>c</kbd> to Focus Code Map. But when Code Map is open, it obscures the File Explorer. Would it be possible to collapse the code map without using a mouse through a command pallette option that could be mapped to a keyboard shortcut?

**Comment by oleg-shilo** [comment]
Hi @KyleKing, glad to hear about CodeMap being used across IDEs :)
The problem is that I don't see any API for collapsing the tree nodes. You can create the code collapsed or expanded but you cannot control its state programmatically. There are quite a few other typical TreeView features that are just absent in VSCode (e.g. node customizable tooltip). This is rather unfortunate.   

Since you have raised #66668 issue, let me know when it is resolved so I can incorporate it.

**Comment by KyleKing** [comment]
Yeah, it looks like they intend to implement the feature for VSCode, but have performance issues pending a refactor of the tree: https://github.com/Microsoft/vscode/issues/34972#issuecomment-423205007

I'll go ahead and close this since VSCode will likely introduce a collapse-all solution. I'll reopen if there are any relevant updates to the API

**Comment by oleg-shilo** [comment]
Great. Txs
